{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phase2-todo-app.fullname" . }}-backend
  labels:
    {{- include "phase2-todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.targetPort }}
    protocol: TCP
    name: http
    {{- if and (eq .Values.backend.service.type "NodePort") .Values.backend.service.nodePort }}
    nodePort: {{ .Values.backend.service.nodePort }}
    {{- end }}
  selector:
    {{- include "phase2-todo-app.backend.selectorLabels" . | nindent 4 }}
{{- end }}
