apiVersion: v2
name: phase2-todo-app
description: A Helm chart for Phase 2 Multi-User Todo Application with FastAPI backend and Next.js frontend

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed.
appVersion: "1.0.0"
